import type { Metadata } from "next";
import "./globals.css";
import { inter, poppins } from "@/styles/fonts";


export const metadata: Metadata = {
  title: "MERCURIAL Consult",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${poppins.className} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
